name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to upload assets to'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build kicanvas.js
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kicanvas-build
        path: |
          build/kicanvas.js
          build/esbuild-meta.json
        retention-days: 30

    - name: Create release asset on tag
      if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          TAG_NAME="${{ github.event.release.tag_name }}"
        else
          TAG_NAME="${{ github.event.inputs.release_tag }}"
        fi
        gh release upload $TAG_NAME build/kicanvas.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
